"""Configs are stored here"""

from selenium import webdriver
import os

mongo_host = os.getenv('MONGO_HOST')
mongo_username = os.getenv('MONGO_USERNAME')
mongo_password = os.getenv('MONGO_PASSWORD')
mongo_port = os.getenv('MONGO_PORT')

# Set chrome options, completely generated by ai
options = webdriver.ChromeOptions()# --- Headless & Core Performance/Stability Options (already mostly present) ---
options.add_argument("--headless=new") # Modern headless mode (prefer over just --headless)
options.add_argument("--no-sandbox") # Essential for running as root in Docker
options.add_argument("--disable-dev-shm-usage") # Overcomes limited /dev/shm in Docker
options.add_argument("--disable-gpu") # Recommended for headless, especially on Linux
options.add_argument("--disable-extensions") # Disable all extensions
options.add_argument("--disable-background-timer-throttling")
options.add_argument("--disable-backgrounding-occluded-windows")
options.add_argument("--disable-renderer-backgrounding")
options.add_argument("--remote-debugging-port=0") # Use random port
options.add_argument("--disable-web-security") # May be needed for certain JS contexts
options.add_argument("--allow-running-insecure-content") # For mixed content sites
options.add_argument("--disable-features=VizDisplayCompositor")
options.add_argument("--disable-blink-features=AutomationControlled") # Hides navigator.webdriver
options.add_experimental_option("excludeSwitches", ["enable-automation"]) # Removes info bars
options.add_experimental_option('useAutomationExtension', False) # Another layer to hide automation
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36") 
options.add_argument("--window-size=1920,1080") # Full HD standard
options.add_argument("--start-maximized") # Maximizes window upon launch
options.add_argument("--disable-site-isolation-trials") # Can help with some site interactions
options.add_argument("--incognito") # Start in incognito mode (prevents persistent cookies/history)
options.add_argument("--blink-settings=imagesEnabled=false") # Disables image loading
options.add_argument("--disable-javascript") # Disables JavaScript (DANGEROUS: breaks most modern sites)
options.add_argument("--lang=en-US") # Set browser language
options.add_argument("--accept-lang=en-US,en;q=0.9") # Set accepted languages
options.add_argument("--ignore-certificate-errors")
options.add_argument("--ignore-ssl-errors")